# Generated by Django 4.2.25 on 2025-11-15 19:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('activo', models.BooleanField(default=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='periodos.periodoacademico')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='programas.programa')),
            ],
            options={
                'indexes': [models.Index(fields=['periodo'], name='idx_grupo_periodo')],
            },
        ),
    ]
