# Generated by Django 4.2.25 on 2025-11-01 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EspacioFisico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('recursos', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='horario.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='horario.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoEspacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_admin', to='horario.usuario')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='horario.espaciofisico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_solicitados', to='horario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioFusionado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_estudiantes', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados', to='horario.asignatura')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_fusionados', to='horario.usuario')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados', to='horario.espaciofisico')),
                ('grupo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_1', to='horario.grupo')),
                ('grupo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_2', to='horario.grupo')),
                ('grupo3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_3', to='horario.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_estudiantes', models.IntegerField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='horario.asignatura')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_docente', to='horario.usuario')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='horario.espaciofisico')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='horario.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='horario.periodoacademico'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='horario.programa'),
        ),
        migrations.CreateModel(
            name='EspacioRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacio_recursos', to='horario.espaciofisico')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurso_espacios', to='horario.recurso')),
            ],
        ),
        migrations.AddField(
            model_name='espaciofisico',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='horario.sede'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuario_rol'),
        ),
        migrations.AddIndex(
            model_name='prestamoespacio',
            index=models.Index(fields=['espacio', 'fecha'], name='idx_prestamo_espacio_fecha'),
        ),
        migrations.AddConstraint(
            model_name='prestamoespacio',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_prestamo_horas'),
        ),
        migrations.AddConstraint(
            model_name='horariofusionado',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_horario_fusionado_horas'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['espacio'], name='idx_horario_espacio'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['docente'], name='idx_horario_docente'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_horario_horas'),
        ),
        migrations.AddIndex(
            model_name='grupo',
            index=models.Index(fields=['periodo'], name='idx_grupo_periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='espaciorecurso',
            unique_together={('espacio', 'recurso')},
        ),
    ]
