# Generated by Django 4.2.25 on 2025-11-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('asignaturas', '0001_initial'),
        ('espacios', '0001_initial'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaciofisico',
            name='sede',
        ),
        migrations.AlterUniqueTogether(
            name='espaciorecurso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='espaciorecurso',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='espaciorecurso',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='prestamoespacio',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='prestamoespacio',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='prestamoespacio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='horario',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='asignaturas.asignatura'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_docente', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='espacios.espaciofisico'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='grupos.grupo'),
        ),
        migrations.AlterField(
            model_name='horariofusionado',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados', to='asignaturas.asignatura'),
        ),
        migrations.AlterField(
            model_name='horariofusionado',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_fusionados', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='horariofusionado',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados', to='espacios.espaciofisico'),
        ),
        migrations.AlterField(
            model_name='horariofusionado',
            name='grupo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_1', to='grupos.grupo'),
        ),
        migrations.AlterField(
            model_name='horariofusionado',
            name='grupo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_2', to='grupos.grupo'),
        ),
        migrations.AlterField(
            model_name='horariofusionado',
            name='grupo3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fusionados_3', to='grupos.grupo'),
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='EspacioFisico',
        ),
        migrations.DeleteModel(
            name='EspacioRecurso',
        ),
        migrations.DeleteModel(
            name='Facultad',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='PeriodoAcademico',
        ),
        migrations.DeleteModel(
            name='PrestamoEspacio',
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
        migrations.DeleteModel(
            name='Recurso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
